### ISSUE TITLE
Using mod_zip with gzipped s3 files

### ISSUE THREAD

**Issue by kronok** [irasnyd/nginx_s3_streaming_zip#3]
I'd love to be able to store my files in s3 as gzipped files and stream them to a zip using mod_zip.

People say mod_zip actually has some performance issues when dealing with gzipped files, but while experimenting with it, I realized that mod_zip won't decompress the file(s) on the fly from s3 when putting them in a zip.

What actually happens is I get a zip of gzipped files. I confirmed it by renaming one of the files to file.gz and was able to decompress it into a usable file.

Works perfect if I just request the files from s3 in a normal browser without involving mod_zip.

Has anyone played with this idea and have any experience with it? I'm likely going to just be storing my files in their raw format, but would love to hear if this is feasible because my files can be compressed by about half their size if I gzip them. I'm particularly interested if this is even possible, and if the performance issues are really that bad.

(I'm posting this here rather than on mod_zip because I think I think using s3 and mod_zip is rare)

**Comment by irasnyd** [comment]
Hey,

This example code / project just takes a bunch of files from S3 and builds a ZIP "on the fly" and sends that out to clients. This was built so that we could serve ZIP archives to clients without needing any temporary storage space. The mod_zip extension build ZIP archives, which is a different format than gzip archives. (In case you didn't know that.)

I haven't ever tried to have NGINX gunzip compressed files before serving them to clients, but the documentation says it is possible. See here: https://nginx.org/en/docs/http/ngx_http_gunzip_module.html#gunzip

I think you could force NGINX to fetch the files from S3, gunzip them, have mod_zip build the ZIP archive on the fly, and send it to the client by adding the following to the NGINX configuration:

```
proxy_set_header Accept-Encoding "";
gunzip on;
```

You might need to do that it two parts to get it to work:
1) a `location` directive that hides the Accept-Encoding header and then internally proxies to
2) another `location` directive that has the `gunzip on` and then internally proxies to
3) the S3 location (the listener on port 3333 in the example code)

I hope that helps you get it figured out.

**Comment by kronok** [comment]
Nice, I tried messing with `proxy_set_header Accept-Encoding "";` with all kinds of values, but I hadn't thought of the combination with the gunzip module. It makes sense.

I'll try recompiling my nginx with that gunzip module and see if I can make it work. I'll report back if I get it working and see how the performance is. I'm sure there'll be someone else out there that wants this same setup.

**Comment by irasnyd** [comment]
Thanks, please let me know how it works out!

I built this repo as an example of how to build an archive on the fly, rather than needing a bunch of temporary storage space to build the archive into. Every other example I could find online did it the naive way using temporary storage. (We would have needed hundreds of GB of temporary space, which wasn't cost effective for us on AWS.)

If you want to see the real world example of this project, you can see my current employer's data archive:

- https://archive-api.lco.global/frames/ (raw API, you'll see signed URLs directly to the raw data on S3, and you can download them one at a time if you want)
- https://archive.lco.global/ (the "pretty" user interface, you can select a bunch of files and click the "download" button at the top to get the ZIP version)

We haven't noticed any performance problems with mod_zip. We've been using it for at least 3 years now. We currently handle up to about 2000 requests per minute no problem. That's all our customers demand, so it's good enough for us.

**Comment by kronok** [comment]
Had time to really dig in and report back. I ended up having the full s3 link generated on my backend, so I removed ngx_aws_auth since it would have just been re-generating a new link. I should note that it's easier to just use ngx_aws_auth and not have to pass all the original headers and stuff and try not to lose anything, but for my particular issue, I really needed to pass everything. So for anyone needing to do that exact thing, this should work great.

Here's what ended up working for me:
```
// in my main server block
	location /s3 {
		rewrite /s3/(.*) /$1 break;
		
		resolver 8.8.8.8 valid=30s;
		resolver_timeout 10s;
		proxy_set_header Accept-Encoding "";
		proxy_http_version 1.1;
		proxy_hide_header X-Archive-Files;

		proxy_intercept_errors on;

		# Do not convert HEAD into GET
		proxy_cache_convert_head off;       

		# Pass along Authorization credentials to upstream S3
		proxy_set_header Authorization $http_authorization;

		# proxy_cache_purge $purge_method;

		proxy_cache_bypass $http_cachepurge;

		# Since head conversion is disabled, the request_method is included in the proxy_cache_key
		proxy_cache_key  "$scheme$proxy_host$request_method$request_uri$is_args$args";

		# GET and HEAD are cached by default
		proxy_cache_methods GET HEAD;

		# Cache all 200 OK's for 24 hours
		proxy_cache_valid  200 24h;

		# Use stale cache file in all errors from upstream if we can
		proxy_cache_use_stale  error timeout updating http_500 http_502 http_503 http_504;

		# Lock the cache so that only one request can populate it at a time
		proxy_cache_lock    on;
		proxy_cache_revalidate on;
		add_header             Cache-Control max-age=31536000;

		# Set back a nice HTTP Header to indicate what the cache status was
		add_header             X-Cache-Status $upstream_cache_status;

		proxy_pass http://my.server.ip.address:8082/$1;
	}

```

then we create a new server to listen for the proxy_pass in the last line above (these can both be in the same site file)
```
server {
        listen my.server.ip.address:8082;
	server_name mydomain.com;

	location / {
		resolver 8.8.8.8 valid=30s;
		resolver_timeout 10s;
		proxy_set_header Accept-Encoding "";
		gunzip on;
		gzip off;
		gzip_proxied off;
		proxy_pass http://mys3storage.s3.amazonaws.com;

		   # Do not convert HEAD into GET
		   proxy_cache_convert_head off;       

		   # Pass along Authorization credentials to upstream S3
		   proxy_set_header Authorization $http_authorization;

		  # proxy_cache_purge $purge_method;

		   proxy_cache_bypass $http_cachepurge;

		   # Since head conversion is disabled, the request_method is included in the proxy_cache_key
		   proxy_cache_key  "$scheme$proxy_host$request_method$request_uri$is_args$args";

		  # GET and HEAD are cached by default
		   proxy_cache_methods GET HEAD;

		  # Cache all 200 OK's for 24 hours
		   proxy_cache_valid  200 24h;

		  # Use stale cache file in all errors from upstream if we can
		   proxy_cache_use_stale  error timeout updating http_500 http_502 http_503 http_504;

		  # Lock the cache so that only one request can populate it at a time
		   proxy_cache_lock    on;
		   proxy_cache_revalidate on;

		   add_header             Cache-Control max-age=31536000;

		  # Set back a nice HTTP Header to indicate what the cache status was
		   add_header             X-Cache-Status $upstream_cache_status;
	}

    }
```
and that works great for me thus far. It's been in production for about 3 months and no complaints.

Anything that's stored in s3 that's pre-gzipped gets unzipped on the fly with nginx with the `gunzip on;` line. Everything else is there so all of the headers and such get passed properly.
